import type { Metadata } from 'next';
import '../styles/global.css';
import SideBar from '@/components/SideBar/SideBar';

export const metadata: Metadata = {
  title: 'What to cook',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-row justify-content-between bg-layout-bg bg-cover bg-center h-screen w-screen"
        style={{backgroundImage: "url('/images/4d91829c061855aa7f9f4a23f1821fbd.jpeg')"}}
        >
          <SideBar/>
          <main className='w-full'>{children}</main>
        </div>
      </body>
    </html>
  );
}
